### ISSUE TITLE
[FEAT] 전체 Guide View 설계

### ISSUE THREAD

**Issue by i-colours-u** [SOPT-29th-Joint-Seminar-1/iOS-Client#10]
## 📌  Feature Issue
Guide View 뷰 설계하기 ! !

ScrollView로 할까, TableView로 할까.. 고민하다가
나중에 아래와 같이 펼치는 뷰가 존재해서,
<img width="925" alt="스크린샷 2021-11-16 오전 2 46 47" src="https://user-images.githubusercontent.com/60260284/141829540-e178bc40-ae22-46f3-9f5f-7431d60fdc36.png">
TableView로 잡기로 결정..!

## 📝  To-do
▶️ Home News TVC 
- [x] 전체 테이블뷰 구성하기
- [x] 네비바 추가하기
- [x] 타이틀 헤더뷰 추가하기(검색바까지)
- [x] 가격 차트뷰 추가하기
- [x] 이용방법 뷰 추가하기
- [x] 유의사항 뷰 추가하기
- [x] 세탁과정 뷰 추가하기
- [x] ShortCut 버튼 추가하기
- [x] 제일 하단에 신청하기 버튼 고정해두기
