### ISSUE TITLE
[FEAT] Guide CategoryList Cell 

### ISSUE THREAD

**Issue by i-colours-u** [SOPT-29th-Joint-Seminar-1/iOS-Client#20]
## 📌  Feature Issue
<img width="499" alt="스크린샷 2021-11-16 오후 4 11 39" src="https://user-images.githubusercontent.com/60260284/141937940-3642cffd-bdec-4e55-8617-8dbe9f50302f.png">

카테고리 선택 (CV) + 상품 목록 (TV)로 구현하기
## 📝  To-do
▶️ 카테고리 리스트 만들기
- [x] 카테고리 list CV로 만들기
- [x] 상품목록 TV로 만들기
- [x] 카테고리 list 선택/비선택 처리하기
- [x] 카테고리 선택했을때 상품목록 갱신하기

## 📰 Related Issues

#10
