### ISSUE TITLE
[FEAT] Guide Warning Cell

### ISSUE THREAD

**Issue by i-colours-u** [SOPT-29th-Joint-Seminar-1/iOS-Client#26]
## 📌  Feature Issue
<img width="983" alt="스크린샷 2021-11-17 오전 12 08 42" src="https://user-images.githubusercontent.com/60260284/142010922-7afd5e20-ff74-48ea-89f5-960d4b5695d9.png">

## 📝  To-do
▶️ Warning Cell 만들기
- [x] 눌렀을때, 접고 필수있도록 뷰 동적으로 설계
- [x] 눌렀을때,접었을때 화살표 아래 위 바꾸기
- [x] 텍스트뷰에 내용 넣기
## 📰 Related Issues

#10
