### ISSUE TITLE
[FEAT] Bottom Floating Shortcut Button

### ISSUE THREAD

**Issue by i-colours-u** [SOPT-29th-Joint-Seminar-1/iOS-Client#31]
## 📌  Feature Issue
<img width="484" alt="스크린샷 2021-11-17 오전 2 31 10" src="https://user-images.githubusercontent.com/60260284/142035774-954d363f-4df1-4c29-bead-70da88a4f8be.png">
## 📝  To-do

▶️ shortcut button 만들기
- [x] 가격표 누르면 가격표가 상단에 위치하도록
- [x] 이용방법 누르면 이용방법이 상단에 위치하도록
- [x] 세탁 과정 누르면 세탁 과정이 상단에 위치하도록,
- [x] 스크롤 좌표에 따라 selected/unselected 구분

## 📰 Related Issues
#10
