### ISSUE TITLE
[FEAT] Header View

### ISSUE THREAD

**Issue by hellozo0** [SOPT-29th-Joint-Seminar-1/iOS-Client#5]
## 📌  Feature Issue

테이블뷰의 첫번째 Cell인 HeaderView(TVC) 만들기

## 📝  To-do
▶️ Home Header TVC
- [x] #43
- [x] #44
- [ ] 다른 곳 눌렀을 회색 배경 해제
- [x] 파란 버튼 눌렀을 시 페이지 이동 
- [x] 에셋추가
- [x] HomeTV에 xib 연결
