### ISSUE TITLE
[FEAT] EventView

### ISSUE THREAD

**Issue by hellozo0** [SOPT-29th-Joint-Seminar-1/iOS-Client#6]
## 📌  Feature Issue

Event View 구현

## 📝  To-do
▶️ HomeEventTVC
- [x] 레이아웃 및 UI
- [x] UICollection View 레이아웃 및 Xib 작업
- [x] UIPageControl
- [ ] UIScrollViewDelegate 사용해서 스크롤 지점 체크
- [ ] Timer 사용해서 5초마다 넘어가도록 자동으로(스크롤지점세팅해서 넘겨주는 방법..!)
- [x] 에셋추가
